### ISSUE TITLE
As a comittee member, I want to use emojis in my news stories, so that i can better express myself

### ISSUE THREAD

**Issue by x183** [cthit/chalmers.it#1]
- [ ] Have support for emojis, if not all unicode chars

**Comment by GAsplund** [comment]
Just providing a quick update to say that it seems like we will be able to provide support for Unicode characters, and therefore also emojis:
![image](https://github.com/cthit/chalmers.it/assets/7264745/ce8d4f62-d2ad-43af-b54a-21665bbb85c1)

**Comment by x183** [comment]
> Just providing a quick update to say that it seems like we will be able to provide support for Unicode characters, and therefore also emojis: ![image](https://user-images.githubusercontent.com/7264745/282155114-ce8d4f62-d2ad-43af-b54a-21665bbb85c1.png)

This looks amazing! Great job :heart_eyes:
