### ISSUE TITLE
8bit Bli medlems länk (https://ebas.sverok.se/Signups/index/8599)

### ISSUE THREAD

**Issue by GargisGargis** [cthit/chalmers.it#111]
### ⚠ Related problems

Länkar inte till bli medlem sidan

### 📝 Description

https://ebas.sverok.se/Signups/index/8599

**Comment by GAsplund** [comment]
Verkar som att vi har ännu ett problem med att våran input sanitizer är för aggressiv. Lägger upp en fix senare idag
