### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by affe4ever** [cthit/chalmers.it#128]
### 📝 Describe the bug

DateIT länken längst ner på sidan e broken https://chalmers.it/pages/services
istället för https://date-it.se/ leder den till https://chalmers.it/pages/date-it.se

### 🔄 To Reproduce

Open site, click link at the bottom of the site :D

### 📷 Screenshots

![image](https://github.com/user-attachments/assets/d3d0e29a-23cd-49a0-9bfc-a2c348f51bb0)

**Comment by GAsplund** [comment]
Fixat!
