### ISSUE TITLE
Make header images center on middle

### ISSUE THREAD

**Issue by erikpersson0884** [cthit/chalmers.it#4]
### Description

Currently the header images starts at the left side and shows as much as they can of the image. This causes the website to cut people out that stand on the right side of some images while there are still a lot of space on the left side. (styrITs image is a good example) Centering the image in the middle would propably solve this

**Comment by GAsplund** [comment]
While this is a valid issue and suggestion for the rewrite of chalmers.it, and correct me if I'm wrong, but I think it relates more to the [current version](https://github.com/cthit/chalmersit-rails).
If you want, you may keep this issue open for the future development of this rewrite.
