### ISSUE TITLE
As a gemene teknolog, I want a page for the budget and activity-plans, so that I can easily find them on the site

### ISSUE THREAD

**Issue by erikpersson0884** [cthit/chalmers.it#41]
### Description

Currently you have to access the division meeting protocol and search for budgets and activity-plans to find them. 

Having a page on the site where you can find them would make it much easier. 
Having documents automaticly uploaded to this page when they are submitted for the division meeting would make it no extra work for the commitees

Including a function to filter based on years/commitees would also be helpful in this page

### Definition of Done

- [ ] There is a page containing all budgets and activity plans

**Comment by Krysset** [comment]
I like this 👍🏻

**Comment by GAsplund** [comment]
Currently looking at getting this implemented! To me it sounds like it would be most useful if it could be used for all kinds of documents. Therefore I'm looking at categorizing these documents into different types, but I am unsure which types would be the best.

Currently I'm thinking something along the lines of:
- Meeting protocols
- Budgets
- Business plans (verksamhetsplaner)
- Financial reports (ekonomiska berättelser)
  - (Maybe this should include audit reports (revisionsberättelser)?)
- Business reports (verksamhetsberättelser)
- Miscellaneous

What do you think, is there anything that should be added/removed?
