### ISSUE TITLE
Image resizing in news posts

### ISSUE THREAD

**Issue by Krysset** [cthit/chalmers.it#5]
### Description

It would be nice to able to resize uploaded images to news posts.

**Comment by GAsplund** [comment]
Currently, you can add custom sizing to an image by using an `<img>` tag with custom width and height properties, along with hard maximum width and height values. Do you think that this fulfills your request, or did you have something more in mind?

**Comment by GAsplund** [comment]
Closing as images now have a max height (and because you should be able to set an image size lower than the maximum allowed). Feel free to open again if you had another solution in mind.
